### ISSUE TITLE
Error in CloudFormation template for infra set-up

### ISSUE THREAD

**Issue by nsubrahm-aws** [aws-samples/opensource-4g-core-eks#1] opened 2021-04-19 03:44 UTC
I received the following error when I launched the template for infra set-up

```bash
The Parameter Group docdbparametergroup-open5gs with DBParameterGroupFamily docdb3.6 cannot be used for this instance. Please use a Parameter Group with DBParameterGroupFamily docdb4.0 (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterCombination; Request ID: a21f5d76-07cd-4ef4-8f3b-80d94de1ff6c; Proxy: null)
```

Changing the version of DocumentDB to `4.0` works.

**Comment by infinitydon** [comment] 2021-04-20 10:27
@nsubrahm-aws Thanks for reporting this but I have not been able to reproduce this..

![image](https://user-images.githubusercontent.com/6318992/115381280-b0b8bb00-a1d3-11eb-9cc4-61850b89e49e.png)

Can you give more details on the parameters you used?

**Comment by jungy-aws** [comment] 2021-05-29 00:42
@nsubrahm-aws Thanks for the report. This has been fixed in 
https://github.com/aws-samples/opensource-4g-core-eks/commit/f83de8b356bf8a3204b1e50864919374d67816fc

As written in the commit, it was because DocumentDB default engine version updated to 4.0, and this caused mismatch with DBParameterGroup family version.It can be fixed either 1) updating DBParameterGroup family version to be 4.0, or 2) DBCluster EngineVersion to be 3.6. As guided in below recommendation, I have added EngineVersion in DBCluster with matching it to be family version, 3.6.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-docdb-dbcluster.html#cfn-docdb-dbcluster-engineversion

**Closed by jungy-aws** 2021-05-29 00:42 UTC
